### ISSUE TITLE
Gremlin Java Client Demo no longer works

### ISSUE THREAD

**Issue by jfassad** [aws-samples/amazon-neptune-samples#67]
Connections through nlb with iam-auth and enable-ssl no longer works

timeouts during handshake.

**Comment by iansrobinson** [comment]
Hi @jfassad  - thanks for reporting this. Can you tell me which region you were running in, and which Neptune engine version you are running? I'll then try and reproduce. Thanks, ian

**Comment by jfassad** [comment]
Hello @iansrobinson . region is us-east-1 , neptune engine is 1.0.4.1.R2 
It appears the problem might be related to something in the AWS NLB .
I've replaced the NLB for a simpleproxy running in an EC2 instance and the problem went away.

**Comment by jfassad** [comment]
@iansrobinson, I made another test. I've created a new NBL with TCP listener and it works. The problem happens only using NBL with a TLS listener.

**Comment by andrew-haus** [comment]
I was able to reproduce this locally as well. 

Neptune engine version - 1.0.5.1
Region - us-west-2

We do not have a NLB and upgrading our gremlin library to 4.3.13 seems to have fixed the issue so far. 

Exception below:
```
Caused by: org.apache.tinkerpop.gremlin.driver.exception.ConnectionException: Could not complete connection setup to the server. Ensure that SSL is correctly configured at both the client and the server. Ensure that client WebSocket handshake protocol matches the server. Ensure that the server is still reachable.
	at org.apache.tinkerpop.gremlin.driver.Channelizer$WebSocketChannelizer.connected(Channelizer.java:268) ~[gremlin-driver-3.4.11.jar:3.4.11]
	at org.apache.tinkerpop.gremlin.driver.Connection.<init>(Connection.java:120) ~[gremlin-driver-3.4.11.jar:3.4.11]
	at org.apache.tinkerpop.gremlin.driver.ConnectionPool.lambda$new$0(ConnectionPool.java:102) ~[gremlin-driver-3.4.11.jar:3.4.11]
	at java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1736) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	... 3 more
Caused by: io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms
	at io.netty.handler.ssl.SslHandler$7.run(SslHandler.java:2112) ~[netty-handler-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
	... 1 more
```

**Comment by vicwolk** [comment]
> I was able to reproduce this locally as well.
> 
> Neptune engine version - 1.0.5.1 Region - us-west-2
> 
> We do not have a NLB and upgrading our gremlin library to 4.3.13 seems to have fixed the issue so far.
> 
> Exception below:
> 
> ```
> Caused by: org.apache.tinkerpop.gremlin.driver.exception.ConnectionException: Could not complete connection setup to the server. Ensure that SSL is correctly configured at both the client and the server. Ensure that client WebSocket handshake protocol matches the server. Ensure that the server is still reachable.
> 	at org.apache.tinkerpop.gremlin.driver.Channelizer$WebSocketChannelizer.connected(Channelizer.java:268) ~[gremlin-driver-3.4.11.jar:3.4.11]
> 	at org.apache.tinkerpop.gremlin.driver.Connection.<init>(Connection.java:120) ~[gremlin-driver-3.4.11.jar:3.4.11]
> 	at org.apache.tinkerpop.gremlin.driver.ConnectionPool.lambda$new$0(ConnectionPool.java:102) ~[gremlin-driver-3.4.11.jar:3.4.11]
> 	at java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1736) ~[?:?]
> 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java) ~[?:?]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
> 	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[?:?]
> 	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[?:?]
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
> 	... 3 more
> Caused by: io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms
> 	at io.netty.handler.ssl.SslHandler$7.run(SslHandler.java:2112) ~[netty-handler-4.1.72.Final.jar:4.1.72.Final]
> 	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
> 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
> 	... 1 more
> ```

I believe you meant version `3.4.13` instead of `4.3.13` and, either way, the problem still lingers. Plus, the timeout is from netty and is untouchable. Any other timeouts (even the 15s one) don't mean much, because the netty 10s timeout takes place. 

Anyway, this problem is still happening now and it doesn't matter if we're using NLB, simpleproxy or anything else. It seems to happen randomly, with a higher rate of not completing the handshake.

**Comment by triggan** [comment]
There's been a lot of work in the open source Apache Tinkerpop Gremlin Java client in recent years to surface various connection issues and exceptions that may have been obfuscated [1].  Most of the Neptune engine versions mentioned in this thread are no longer supported (or available) and most of the recent versions now support TinkerPop 3.6.x or 3.7.x.

Closing this out as stale. If you need additional assistance, please do reach out to us via re:Post: https://repost.aws/tags/TAxVAEdWg1SrS0lClUSX-m_Q/amazon-neptune

[1] https://tinkerpop.apache.org/docs/current/upgrade/#_gremlin_driver_host_availability
